function mode(){document.getElementById("hentai").classList.toggle("w");this.classList.toggle("on");}
document.querySelector('.btn-mode').addEventListener('click',mode);function menu(){document.getElementById("hd").classList.toggle("on");this.classList.toggle("on");}
document.querySelector('.menu-btn').addEventListener('click',menu);jQuery(document).ready(function($){var search_opts={callback:function(value){search(value);},wait:400,highlight:true,allowSubmit:false,captureLength:2};$("#search-anime").typeWatch(search_opts);var searchHover=function(e){if($(e.target).closest('#search-box').length===0){$('.sub-menu').parent('.search').removeClass('on');$(document).unbind("click",searchHover);}}
$("#search-anime").on('click',function(e){if(!$("#search-box").hasClass("on")){$("#search-box").addClass("on");setTimeout(function(){$(document).bind("click",searchHover);},10)}});$("#search-anime").on('input',function(){var searchTerm=$(this).val();if(searchTerm.length>1){$('#search-results')('<li>Buscando...</li>');}else{$('#search-results')('<li>Escribe almenos 2 caracteres...</li>');}});$(".vote-list button").on("click",function(){if(!is_auth){alert("Necesitas iniciar sesión para esto");return;}
$.post('/api/voteAnime',{anime_id:anime_id,vote:$(this).attr("data-vote")},function(data){alert("Gracias por tu voto, el rating tarda un poco en verse afectado.");},"json").fail(function(){alert("Ha ocurrido un error");});});$(".btn-favorites").on("click",function(){if(!is_auth){alert("Necesitas iniciar sesión para esto");return;}
var anime_id=$(this).attr("data-id");var favorite=$(this).attr("data-favorite");var mode=favorite==0?1:0;var current_btn=$(this);$.post('/api/addFavorite',{anime_id:anime_id,favorite:mode},function(data){if(mode==1){current_btn.addClass("on");current_btn.attr("data-favorite",1);}else{current_btn.removeClass("on");current_btn.attr("data-favorite",0);}},"json").fail(function(){alert("Ha ocurrido un error");});});$(".remove-favorites").on("click",function(){if(!is_auth){alert("Necesitas iniciar sesión para esto");return;}
var anime_id=$(this).attr("data-id");var $this=$(this);$.post('/api/addFavorite',{anime_id:anime_id,favorite:0},function(data){$this.closest(".hentai").remove();},"json").fail(function(){alert("Ha ocurrido un error");});});function search(value){if(value.length<2)
return;$.post('/api/search',{value:value},function(data){var results_box=$("#search-results");var append='';results_box.empty();if(data.length){var limit=(data.length>5)?5:data.length;for(var i=0;i<limit;i++){append+='<li><a href="/hentai-'+data[i].slug+'"><figure><img src="/uploads/portadas/48x65/'+data[i].id+'.jpg" alt="'+data[i].title+'"></figure> '+data[i].title+'</a></li>';}
results_box.append(append);}else{results_box.append('<li>No se encontraron resultados</li>');}},"json");}
initEpisode=function(){$("#episode-options").empty();for(x in videos)
$("#episode-options").append('<li><a href="#" data-id="'+x+'" title="'+videos[x][0]+'"><i class="fa fa-play"></i> '+videos[x][0]+'</a></li>');setTimeout(function(){$("#episode-options li:first a").trigger("click");},100);};$(document).on("click","#episode-options li a",function(e){e.preventDefault();var video=videos[$(this).data('id')];$("#episode-options li a").removeClass("on");$(this).addClass("on");$('#repro')('<iframe width="100%" height="100%" src="'+video[1]+'" frameborder="0" allowfullscreen></iframe>');return false;});$('.latest-hentais .slider').slick({dots:true,arrows:false,fade:true,slidesToShow:1,slidesToScroll:1,infinite:false});$('.aa-drp').each(function(){var $AADrpdwn=$(this);$('.aa-lnk',$AADrpdwn).click(function(e){e.preventDefault();$AADrpdDv=$('.aa-cnt',$AADrpdwn);$AADrpdDv.parent('.aa-drp').toggleClass('on');$('.aa-cnt').not($AADrpdDv).parent('.aa-drp').removeClass('on');return false;});});$('.aa-tgl').on('click',function(){var shwhdd=$(this).attr('data-tgl');$('#'+shwhdd).toggleClass('on');$(this).toggleClass('on');});$('.aa-tgle').on('click',function(){var shwhdde=$(this).attr('data-tgle');$('#'+shwhdde).toggleClass('on');$(this).toggleClass('on');});$('.aa-tglo').on('click',function(){var shwhddo=$(this).attr('data-tglo');$('#'+shwhddo).toggleClass('on');$(this).toggleClass('on');});$(document).on('click',function(e){if($(e.target).closest('.aa-cnt').length===0){$('.aa-cnt').parent('.aa-drp').removeClass('on');}});$('.aa-tbs a').click(function(e){e.preventDefault();var $this=$(this),tabgroup='#'+$this.parents('.aa-tbs').data('tbs'),others=$this.closest('li').siblings().children('a'),target=$this.attr('href');others.removeClass('on');$this.addClass('on');$(tabgroup).children().removeClass('on');$(target).addClass('on');});$('.aa-mdl').on('click',function(){var shwhddb=$(this).attr('data-mdl');$('#'+shwhddb).toggleClass('on');$('body').toggleClass('mdl-on');$(this).toggleClass('on');});$(document).keyup(function(e){if(e.keyCode===27){$('body').removeClass('mdl-on');$('.mdl').removeClass('on');}});});